services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
- docker-compose -f docker-compose-build.yaml build --parallel

- docker tag udagram-api-feed lvdinh/udagram-api-feed:v1
- docker tag udagram-api-user lvdinh/udagram-api-user:v1
- docker tag udagram-frontend lvdinh/udagram-frontend:v1
- docker tag udagram-reverseproxy lvdinh/udagram-reverseproxy:v1

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

- docker push lvdinh/udagram-api-feed:v1
- docker push lvdinh/udagram-api-user:v1
- docker push lvdinh/udagram-frontend:v1
- docker push lvdinh/udagram-reverseproxy:v1
