apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed 
        image: lvdinh/udagram-api-feed:latest
        imagePullPolicy: Always  
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
            - secretRef:
                name: env-secret
                optional: false
            - configMapRef:
                name: env-configmap
                optional: false
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret